Update Daisy profile
mluggy/techmap pull request #20
Opened 2024-08-12 07:49 UTC by nir-hemed

Fixed address and added additional attributes

2024-08-12 07:52 UTC, nir-hemed commented on companies/515820587.json
> +      "lat": 32.067030,
I'm not sure how the map extracts lat long from the address but here are the correct values from Google Maps:
lat: 32.066983, long: 34.790784

2024-08-12 12:36 UTC, mluggy requested changes
Logo must reside locally. If you prefer your own please upload as logos/{filename}.webp (can be png, jpg or gif as well). Make sure it is 200x200px

2024-08-27 14:59 UTC, nir-hemed commented
Fixed per your request

2024-08-27 15:08 UTC, mluggy approved these changes

2024-08-27 15:08 UTC, merged